#!/usr/bin/env Rscript --vanilla
## -*- r -*-

args <- commandArgs(TRUE)
vv <- Sys.getenv("VERSIONNUM")
if ("" != vv) {
  desc <- read.dcf("pkg/DESCRIPTION")
  desc[,"Version"] <- vv
  write.dcf(desc, file="pkg/DESCRIPTION")
}  else {
  v <- system("svnversion", TRUE)

  if (regexpr("Uncommitted.*", v) > 0) {
    revision <- as.integer(Sys.time())
  } else if (regexpr(".*M", v) > 0) { ## Modified
    revision <- as.integer(Sys.time())
  } else {
    revision <- max(as.integer(strsplit(v, ":")[[1]]))
  }
  if (length(args) == 0) {
    major <- 0
    minor <- 0
  } else if (length(args) == 1) {
    major <- as.integer(args[1])
    minor <- 0
  } else {
    major <- as.integer(args[1])
    minor <- as.integer(args[2])
  }
  desc <- read.dcf("pkg/DESCRIPTION")
  desc[,"Version"] <- sprintf("%i.%i-%i", major, minor, revision)
  write.dcf(desc, file="pkg/DESCRIPTION")
}



